import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface":                      "#f9f9fa",
        "secondary":                    "#855300",
        "on-primary-fixed-variant":     "#3f465c",
        "tertiary-fixed":               "#d8e2ff",
        "primary-container":            "#131b2e",
        "on-secondary":                 "#ffffff",
        "on-background":                "#1a1c1d",
        "on-primary-container":         "#7c839b",
        "surface-dim":                  "#d9dadb",
        "tertiary-container":           "#001a42",
        "surface-container":            "#eeeeef",
        "outline-variant":              "#c6c6cd",
        "secondary-fixed":              "#ffddb8",
        "surface-bright":               "#f9f9fa",
        "on-surface-variant":           "#45464d",
        "on-surface":                   "#1a1c1d",
        "surface-container-highest":    "#e2e2e3",
        "secondary-fixed-dim":          "#ffb95f",
        "on-error-container":           "#93000a",
        "surface-variant":              "#e2e2e3",
        "background":                   "#f9f9fa",
        "on-secondary-container":       "#684000",
        "primary-fixed-dim":            "#bec6e0",
        "primary":                      "#000000",
        "surface-container-low":        "#f3f3f4",
        "on-primary-fixed":             "#131b2e",
        "on-primary":                   "#ffffff",
        "on-tertiary-container":        "#3980f4",
        "surface-container-lowest":     "#ffffff",
        "outline":                      "#76777d",
        "on-secondary-fixed":           "#2a1700",
        "on-secondary-fixed-variant":   "#653e00",
        "secondary-container":          "#fea619",
        "surface-container-high":       "#e8e8e9",
        "primary-fixed":                "#dae2fd",
        "tertiary-fixed-dim":           "#adc6ff",
        "error-container":              "#ffdad6",
      },
      spacing: {
        "stack-xs":        "4px",
        "stack-sm":        "8px",
        "stack-md":        "16px",
        "stack-lg":        "32px",
        "stack-xl":        "64px",
        "gutter":          "24px",
        "margin-mobile":   "20px",
        "margin-desktop":  "48px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      fontFamily: {
        sans:             ["Manrope", "Inter", "system-ui", "sans-serif"],
        display:          ["Manrope", "sans-serif"],
        "display-lg":     ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "headline-lg":    ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-md":    ["Manrope", "sans-serif"],
        "body-lg":        ["Manrope", "sans-serif"],
        "body-md":        ["Manrope", "sans-serif"],
        "label-md":       ["Manrope", "sans-serif"],
        "label-sm":       ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-lg":         ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile":  ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg":        ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md":        ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg":            ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":            ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md":           ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm":           ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      boxShadow: {
        "luxe":    "0 4px 6px -1px rgba(0,0,0,0.05), 0 20px 40px -4px rgba(0,0,0,0.08)",
        "luxe-lg": "0 8px 12px -2px rgba(0,0,0,0.06), 0 30px 60px -6px rgba(0,0,0,0.12)",
      },
    },
  },
  plugins: [],
};

export default config;
